# Generated by Django 4.1.7 on 2023-03-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filimapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filim',
            name='img',
            field=models.ImageField(default='abcd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
